### ISSUE TITLE
Call to non-existing methods

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [magespecialist/m2-MSP_TwoFactorAuth#1]
**Steps to reproduce:**
1. ... -> Security Suite -> Two Factor Authentication -> Enable = yes.
2. Save Configuration
3. Flush cache
4. Admin user -> 2FA -> Enable = yes.
5. Save user
6. Now you will be asked for scanning the QR Code, but the image is broken:
![image](https://cloud.githubusercontent.com/assets/17547877/25801362/8ec1b46e-33ed-11e7-9f10-9751da88db54.png)
7. Follow link of the image:
![error](https://cloud.githubusercontent.com/assets/17547877/25801414/cde2b422-33ed-11e7-9595-5f118c932423.png)

Because of the requirement in composer.json `"endroid/qrcode": "^1.7"` it installed version `1.9.3` in which those methods don't exist anymore. Also saw that on their github 1.7 tags don't exists.

So I can think of 2 possible solutions:
1. Fix composer.json to include the correct package version `endriod/qrcode`
2. Update the code to use their new package version (also update composer.json to reflect that version number).

Hopefully you can provide an solution asap :smile: 

Don't think this is really relevant for the issue but:
Tested on latest Magento 2 CE & EE `2.1.6`
Installed version of `endroid/qrcode` = `1.9.3`
Installed version of `msp/twofactorauth` =  `0.1.4`

**Comment by GeoffreyDijkstra** [comment]
Also I couldn't return from the "Scan QR Code" screen by a cancel button or something and had to use your command line command: `php bin/magento msp:security:tfa:disable` to get back in the system :cry:

**Comment by phoenix128** [comment]
Just upgrade endroid/qrcode  via composer.
Seems you are using an outdated module and we have to change our base version in composer.json file. They changed some method name.

**Comment by phoenix128** [comment]
You need version 2.1.x, there was a mistake in our composer.json

**Comment by phoenix128** [comment]
We just fiexed in our composer.json file if you wish to upgrade it.

**Comment by GeoffreyDijkstra** [comment]
Will update and see what happens :smile:

**Comment by GeoffreyDijkstra** [comment]
Thx it works! :tada:
