### ISSUE TITLE
Error during compilation on 2.1.8

### ISSUE THREAD

**Issue by gperis** [magespecialist/m2-MSP_TwoFactorAuth#10]
> MSP\TwoFactorAuth\Controller\Adminhtml\Authy\Authpost
> 		Incorrect dependency in class MSP\TwoFactorAuth\Controller\Adminhtml\Authy\Authpost in /var/www/html/vendor/msp/twofactorauth/Controller/Adminhtml/Authy/Authpost.php
> \Magento\Framework\Event\ManagerInterface already exists in context object
> 

This error comes for every controller. It seems to have been fixed in PR #5 but the code is not in the latest release.

Kind regards,
Giancarlo.

**Comment by phoenix128** [comment]
Same error, but in a different position. Thank you for reporting this.
We are at work on it, we will release a fix in the very next minutes.

**Comment by phoenix128** [comment]
Hello @gperis ,
this has been fixed in 2.0.7, please upgrade.

Regards.

**Comment by gperis** [comment]
@phoenix128 Now it's compiling without any errors. Thank you so much for the amazing job.

Kind regards,
Giancarlo.
