### ISSUE TITLE
Compilation error on Magento 2.2 

### ISSUE THREAD

**Issue by peterjaap** [magespecialist/m2-MSP_TwoFactorAuth#11]
### Preconditions

1. Magento 2.2
2. Latest version of this module

### Steps to reproduce

1. `php bin/magento setup:di:compile` in production mode

### Expected result

1. It should compile

### Actual result

1. This;

```
Interception cache generation... 6/7 [========================>---]  85% 43 secs 248.0 MiBErrors during compilation:
	MSP\TwoFactorAuth\Ui\Component\Form\User\DataProvider
		Incompatible argument type: Required type: string. Actual type: \MSP\TwoFactorAuth\Ui\Component\Form\User\name; File: 
/builds/clientname/clientname/vendor/msp/twofactorauth/Ui/Component/Form/User/DataProvider.php
```

**Comment by phoenix128** [comment]
Hello @peterjaap ,
thank you for reporting this issue. We are a t work to fix it asap.

**Comment by phoenix128** [comment]
Hello @peterjaap ,
please upgrade to 2.0.13 . This has been fixed.

**Comment by peterjaap** [comment]
Great quick response, thanks!!

**Comment by dzima-chyzhou** [comment]
The same error appears on Magento 2.2.3 if you do not specify in phpDoc arguments type in Custom Data Provider.
