### ISSUE TITLE
Module cause 500 on swagger

### ISSUE THREAD

**Issue by maqlec** [magespecialist/m2-MSP_TwoFactorAuth#12]
### Preconditions

1. Magento 2.1.10
2. MSP_SecuritySuite 2.0.1

### Steps to reproduce

1. Try to run swagger 

### Expected result

1. See swagger

### Actual result

1. Error 500

500 : {"message":"Invalid parameter type \"\\MSP\\TwoFactorAuth\\Model\\ProviderInterface[]\".","trace":"#0 \/app\/magento\/vendor\/magento\/framework\/Reflection\/TypeProcessor.php(160): Magento\\Framework\\Reflection\\TypeProcessor->translateTypeName('\\\\MSP\\\\TwoFactorA...')\n#1 \/app\/magento\/vendor\/magento\/module-webapi\/Model\/Config\/ClassReflector.php(103): Magento\\Framework\\Reflection\\TypeProcessor->register('\\\\MSP\\\\TwoFactorA...')\n#2 \/app\/magento\/vendor\/magento\/module-webapi\/Model\/Config\/ClassReflector.php(72): Magento\\Webapi\\Model\\Config\\ClassReflector->extractMethodData(Object(Zend\\Code\\Reflection\\MethodReflection))\n#3 \/app\/magento\/vendor\/magento\/module-webapi\/Model\/ServiceMetadata.php(119): Magento\\Webapi\\Model\\Config\\ClassReflector->reflectClassMethods('\\\\MSP\\\\TwoFactorA...', Array)\n#4 \/app\/magento\/vendor\/magento\/module-webapi\/Model\/ServiceMetadata.php(148): Magento\\Webapi\\Model\\ServiceMetadata->initServicesMetadata()\n#5 \/app\/magento\/vendor\/magento\/module-webapi\/Model\/Rest\/Swagger\/Generator.php(913): Magento\\Webapi\\Model\\ServiceMetadata->getServicesConfig()\n#6 \/app\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest.php(278): Magento\\Webapi\\Model\\Rest\\Swagger\\Generator->getListOfServices()\n#7 \/app\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest.php(214): Magento\\Webapi\\Controller\\Rest->processSchemaRequest()\n#8 \/app\/magento\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(37): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/app\/magento\/vendor\/magento\/framework\/App\/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/app\/magento\/vendor\/magento\/framework\/Interception\/Interceptor.php(74): Magento\\Framework\\App\\Http->launch()\n#11 \/app\/magento\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(70): Magento\\Framework\\App\\Http\\Interceptor->___callParent('launch', Array)\n#12 \/app\/magento\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(63): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\Framewo...', 'launch', Object(Magento\\Framework\\App\\Http\\Interceptor), Array, 'mSPShieldAppInt...')\n#13 \/app\/magento\/vendor\/msp\/shield\/Plugin\/AppInterfacePlugin.php(111): Magento\\Framework\\Interception\\Chain\\Chain->Magento\\Framework\\Interception\\Chain\\{closure}()\n#14 \/app\/magento\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(67): MSP\\Shield\\Plugin\\AppInterfacePlugin->aroundLaunch(Object(Magento\\Framework\\App\\Http\\Interceptor), Object(Closure))\n#15 \/app\/magento\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(63): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\Framewo...', 'launch', Object(Magento\\Framework\\App\\Http\\Interceptor), Array, 'mSPAdminRestric...')\n#16 \/app\/magento\/vendor\/msp\/adminrestriction\/Plugin\/AppInterfacePlugin.php(134): Magento\\Framework\\Interception\\Chain\\Chain->Magento\\Framework\\Interception\\Chain\\{closure}()\n#17 \/app\/magento\/vendor\/magento\/framework\/Interception\/Chain\/Chain.php(67): MSP\\AdminRestriction\\Plugin\\AppInterfacePlugin->aroundLaunch(Object(Magento\\Framework\\App\\Http\\Interceptor), Object(Closure))\n#18 \/app\/magento\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\Interception\\Chain\\Chain->invokeNext('Magento\\\\Framewo...', 'launch', Object(Magento\\Framework\\App\\Http\\Interceptor), Array, 'mSPAntiVirusApp...')\n#19 \/app\/magento\/vendor\/msp\/antivirus\/Plugin\/AppInterfacePlugin.php(104): Magento\\Framework\\App\\Http\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#20 \/app\/magento\/vendor\/magento\/framework\/Interception\/Interceptor.php(142): MSP\\AntiVirus\\Plugin\\AppInterfacePlugin->aroundLaunch(Object(Magento\\Framework\\App\\Http\\Interceptor), Object(Closure))\n#21 \/app\/magento\/var\/generation\/Magento\/Framework\/App\/Http\/Interceptor.php(26): Magento\\Framework\\App\\Http\\Interceptor->___callPlugins('launch', Array, Array)\n#22 \/app\/magento\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#23 \/app\/magento\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#24 {main}"} http://magento.dev/rest/default/schema?services=all

**Comment by phoenix128** [comment]
Hello @maqlec ,
this has been fixed in 2.1.1, please upgrade.

**Comment by maqlec** [comment]
Thx @phoenix128, please update version in security suite:)

**Comment by phoenix128** [comment]
It should be already updated at 2.1.1, don't you see it?

**Comment by maqlec** [comment]
Thank you, I see it now. I don't know why composer update on only one package didn't update the package. But global update did the thing:)
