### ISSUE TITLE
endroid/qrcode is abandoned

### ISSUE THREAD

**Issue by peterjaap** [magespecialist/m2-MSP_TwoFactorAuth#15]
Composer says;

`Package endroid/qrcode is abandoned, you should avoid using it. Use endroid/qr-code instead.`

**Comment by phoenix128** [comment]
Hello @peterjaap ,
thank you for reporting this, we are aware of it and we are finding the best way to get it updated without breaking any bacward compatibility with other modules, since the author left in the new module the same namespace as the old one.

**Comment by phoenix128** [comment]
The module has been updated in the official Magento version: https://github.com/magento/magespecialist_TwoFactorAuth
