### ISSUE TITLE
Question / Feature Request: Force 2FA

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [magespecialist/m2-MSP_TwoFactorAuth#2]
Is it possible to add an way that 2FA is forced? Because now you manually have to enable it for every user and if you don't enable it for one he/she can still log in without 2FA.

**Comment by phoenix128** [comment]
Uhm... this could be a good idea.
We could include something like a "force 2FA for all users", we will work on it.

Meanwhile you can force it with an SQL query:

`update admin_user set msp_tfa_enabled=1;`

This should force 2FA to be activated for each user. They will be prompted with QR code at their first login.

**Comment by GeoffreyDijkstra** [comment]
Nice, thx for the quick replies today :smile:

**Comment by phoenix128** [comment]
We did it, check 1.1.0.

**Comment by GeoffreyDijkstra** [comment]
Awesome, will update the project when I have time and check this new feature :smile:
