### ISSUE TITLE
Some authenticator apps say invalid URL

### ISSUE THREAD

**Issue by peterjaap** [magespecialist/m2-MSP_TwoFactorAuth#6]
Sometimes the QR code generated will not validate. 1Password One Time Password does read the QR code but will generate an invalid code every time. Google Authenticator will give an invalid url warning;

![image](https://user-images.githubusercontent.com/431360/26974145-455f8134-4d1a-11e7-906d-7f6f8e2fc4eb.png)

We tracked it down to the secret being a base32 hash and thus containing three `=` at the end of the string. The created `otpauth://` will then be invalid for some authenticator apps in some situations. 

The fix is to strip out the special characters, thereby generating a valid oauth url everytime.

**Comment by peterjaap** [comment]
See PR #7

**Comment by phoenix128** [comment]
Thank you for your Merge Request, it fixed this issue.
