### ISSUE TITLE
Endless loop with DUO

### ISSUE THREAD

**Issue by piotrekkaminski** [magespecialist/m2-MSP_TwoFactorAuth#8]
I was trying to setup DUO but after enabling I get to the screen with Push/Call/Enter Code and then i approve the push or enter the code and clicking continue takes me back to the Push/Call/Enter Code page. 

Trying to access /admin panel redirects me there again - so i get locked until using the command line to disable 2fa.

**Comment by phoenix128** [comment]
Hello @piotrekkaminski ,
are you on the master branch last version?

**Comment by piotrekkaminski** [comment]
I did composer require just today. I assume this gets the latest?

**Comment by piotrekkaminski** [comment]
but i did get the whole suite (https://github.com/magespecialist/m2-MSP_Security_Suite/blob/master/composer.json)

**Comment by phoenix128** [comment]
Hi @piotrekkaminski ,
yes, it is the latest, we are going to verify this immediately on a brand new 2.1.x Magento install.

**Comment by piotrekkaminski** [comment]
I tried on 2.1.7 CE with Sample Data

**Comment by phoenix128** [comment]
Checking this now.

**Comment by phoenix128** [comment]
Hello @piotrekkaminski ,
please upgrade to 1.2.3 , this is fixed.

P.S: We are about to release version 1.3 with major new features, stay tuned ;)
