### ISSUE TITLE
u2f not working

### ISSUE THREAD

**Issue by piotrekkaminski** [magespecialist/m2-MSP_TwoFactorAuth#9]
1) I was trying with Yubikey and it does not register the device (it worked well with https://demo.yubico.com/). 
2) It also locked me out of admin - bin/magento msp:security:tfa:disable doesn't disable redirect to yubikey registration. 
3) Additionally, there is no way to log in as a different admin when you are stuck on registration page

**Comment by phoenix128** [comment]
Are you using HTTPS in your Magento store? Yubico keys usage is HTTPS restricted.
About logout and login while in 2fa process you are right, we have to provide a way to exit.

**Comment by piotrekkaminski** [comment]
Yes – I have HTTPS via let’s encrypt and it shows as secure page. I also don’t get any console errors or anything
---
update: problems was with subpath store.com/path/admin. @phoenix128 is working on a fix.

**Comment by phoenix128** [comment]
Fixed in 2.0.4 .
